site_name: Pipelining with DevSecOps
site_description: Documentation for Managing a DevSecOps Pipeline with Secure Development and Operations
site_author: Rahul
site_url: https://devsecops.nxio.us/

nav:
- Introduction: 'index.md'
- Contents: 'contents.md'
- Problem statement: 'problem-statement.md'
- Glossary: 'glossary.md'
- Deploying the report: 'deploying-the-report.md'
- Setting up VMs: 'setting-up-vms.md'
- Pipeline setup: 'pipeline-setup.md'
- Software Composition Analysis: 'software-composition-analysis.md'
- Static analysis (SAST): 'static-analysis.md'
- SAST tools comparison: 'sast-tools-comparison.md'
- Dynamic analysis (DAST): 'dynamic-analysis.md'
- Code Linting: 'code-linting.md'
- Software Bill of Materials (SBoM): 'software-bill-of-materials.md'
- Final Pipeline Structure: 'final-pipeline-structure.md'
- Migrating to AWS: 'migrating-to-aws.md'
- Resources and references: 'resources-and-references.md'

theme: 
  name: 'material'
  logo: 'images/logo.png'
  favicon: 'images/logo.png'
  palette:
    primary: 'blue'
  font:
    text: Inter
    code: Roboto Mono

markdown_extensions:
   - attr_list