site_name: Pipelining with DevSecOps

nav:
- Introduction: 'index.md'
- Contents: 'contents.md'
- Problem Statement: 'problem-statement.md'
- Glossary: 'glossary.md'
- Deploying the report: 'deploying-the-report.md'
- Setting up VMs: 'setting-up-vms.md'
- Pipeline Setup: 'pipeline-setup.md'
- Resources and referenes: 'resources-and-references.md'

theme: 
  name: 'material'
  logo: 'images/logo.png'
  favicon: 'images/logo.png'
  palette:
    primary: 'blue'
  font:
    text: Inter
    code: Roboto Mono

markdown_extensions:
   - attr_list